services:
  web:
    image: flask-mongodb-oracle:latest
    env_file:
      - .env
    command: bash -c "
      gunicorn greens.main:app
      --bind 0.0.0.0:8989
      --workers 4
      --reload
      "
    volumes:
      - ./greens:/app/greens
      - ./tests:/app/tests
    ports:
      - "8989:8989"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0.8
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGODB_DATABASE}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}"
    command:
      mongod --quiet --logpath /dev/null
